box_vectors = [ 5.0, 5.0, 5.0,]
dimensions_of_space = 3
number_of_particles = 125
temperature = 1.0417397617619721
potential_energy = 0.0
kinetic_energy = 195.32620533036976
pressure = 1.041739761761972
virial = 0.0
density = 1.0
volume = 125.0
pair_potential_str = "(1-r)**2"
pair_potential_r_cut = 1.0
neighbor_list_skin = 1.0
max_number_of_neighbors = 512
neighbor_list_method_str = "double loop"
energy_method_str = "neighbor list"
force_method_str = "neighbor list"
time_step = 0.01
temperature_target = 1.0
temperature_damping_time = 0.1
number_of_steps = 0
number_of_neighbor_list_updates = 3

